### PR TITLE
Fixes before 1.8.0

### PR DESCRIPTION
**Pull request by bertrand-lorentz**
Various corrections needed for the upcoming 1.8.0.

I'm creating this PR so that you can have a look at the changes as they are made, but it is currently **indicated as a "draft"**, as there are more corrections needed. I'll remove the "draft" status when all expected corrections are there.

### CODE REVIEW

**Review by rouschr — DISMISSED** [review]
I will trust you with those svrl changes as this is your thing.

**Comment by bertrand-lorentz** [comment]
Checks are now green 💚  🎆 
So this is ready for review.

**Comment by rouschr** [comment]
> Checks are now green 💚 🎆 So this is ready for review.

This is great news, I think 1.8 passing all the checks (and new checks) is a very good sign and XML generation will be easier for everyone.

**Review by rouschr — APPROVED** [review]
The diff of fields.json is hard to read but I see the latest changes there, so OK for me.

**Pull request merged**
