### PR TITLE
Prepare release of SDK 1.7.1

### PR DESCRIPTION
**Pull request by bertrand-lorentz**
View templates were all successfully compiled locally with the SDK analyzer, with no relevant error reported.

### CODE REVIEW

**Review by pdonohoe — CHANGES_REQUESTED** [review]
I think somehow EFX lines marked as DRAFT=1 were exported from the database. There are 196 lines (20 lines across the .efx files) which include "TODELETE" in prepare/1.7.1 which are not in release/1.7.1. Can these EFX lines be excluded?

These lines are also in release/1.8.0 :(

**Comment by pdonohoe** [comment]
OK, I removed the TODELETE lines myself and pushed to prepare/1.7.1

**Comment by bertrand-lorentz** [comment]
Thanks for doing the removal.
For 25, 26 and 27, a line removed was the only line under a heading with number 5, so I'm wondering if this is OK.
See for example: https://github.com/OP-TED/eForms-SDK/commit/018ee32f598207e5dcb792df52b7f4c3d6db204e#diff-9b37daff4472ccb6984d9a0a9d925e0c565dbc2169ff3ecdd1f109efddb866a8

**Comment by bertrand-lorentz** [comment]
This now looks OK for me, no errors on view templates from the analyzer.

**Review by pdonohoe — APPROVED** [review]

**Pull request merged**
