### PR TITLE
Fixing artifical limitation on linguistic versions possible to have a…

### PR DESCRIPTION
**Pull request by klakegg**
…s legally valid

### CODE REVIEW

**Comment by bertrand-lorentz** [comment]
Thank you for your suggestion.

The current SDK rules are correct: notices can only be published on TED in one of the 24 EU official languages. This is already the case with the current forms, where Norway has chosen to publish their notices in English, and this won't change with eForms so BT-702 is limited to EU official languages.

This limitation doesn't exist for other fields where a language is specified and the 3 Norwegian languages are available in the codelist for these fields - see https://docs.ted.europa.eu/eforms/latest/reference/code-lists/eforms-language.html

There are other examples within the EU, where the language of the notice is different to the language of the procurement procedure - the most common case is in Catalonia, where the documents and submissions are in Catalan but the notices on TED are in Spanish.

So I'm closing this pull request.

**Comment by klakegg** [comment]
The language used for publishing is not the same as linguistic versions possible to have as legally valid. eForms is the format to express a valid notice and only one of the aspects are related to publishing on TED.

Official description of BT-702: `The language(s) in which this notice is officially available. These linguistic versions are equally legally valid.`

There are no reasons to not allow other languages than the 24 official languages as long as minimum one of the official languages are provided.

**Comment by ferrakaop** [comment]
Thanks for this clarification. It's true it's possible to use the eForms format to handle notices that are not published on TED so you could go beyond the 24 EU languages in BT-702.

But if you submit the notice to TED, it's because you intend to publish it on TED and in this case the Publications Office will need to check that only EU official languages have been used to ensure compliance with the 2014 procurement directives.

You'll need to handle your national needs within your system.  It is fairly common that national systems don't map exactly to the EU formats, e.g. you might refer to national laws in your system then need to map it to the EU directives to satisfy the validation on the legal basis BT in eForms.

**Comment by klakegg** [comment]
> This limitation doesn't exist for other fields where a language is specified and the 3 Norwegian languages are available in the codelist for these fields - see https://docs.ted.europa.eu/eforms/latest/reference/code-lists/eforms-language.html

I have tested this, and when adding Norwegian in addition to English in one of your example, I ended up with the following validation rules triggering:

* BT-163-Tender_C - BT-163-Tender can only be in one of the official languages of the notice
* BT-163-Tender_C - BT-163-Tender can only be in one of the official languages of the notice
* BT-721-Contract_C - BT-721-Contract can only be in one of the official languages of the notice
* BT-721-Contract_C - BT-721-Contract can only be in one of the official languages of the notice
* BT-500-Organization-Company_C - BT-500-Organization-Company can only be in one of the official languages of the notice
* BT-500-Organization-TouchPoint_C - BT-500-Organization-TouchPoint can only be in one of the official languages of the notice
* BT-500-Organization-Company_C - BT-500-Organization-Company can only be in one of the official languages of the notice
* BT-500-Organization-Company_C - BT-500-Organization-Company can only be in one of the official languages of the notice
* BT-500-Organization-Company_C - BT-500-Organization-Company can only be in one of the official languages of the notice
* BT-21-Procedure_C - BT-21-Procedure can only be in one of the official languages of the notice
* BT-24-Procedure_C - BT-24-Procedure can only be in one of the official languages of the notice
* BT-300-Procedure_C - BT-300-Procedure can only be in one of the official languages of the notice
* BT-540-Lot_C - BT-540-Lot can only be in one of the official languages of the notice
* BT-734-Lot_C - BT-734-Lot can only be in one of the official languages of the notice
* BT-99-Lot_C - BT-99-Lot can only be in one of the official languages of the notice
* BT-21-Lot_C - BT-21-Lot can only be in one of the official languages of the notice
* BT-24-Lot_C - BT-24-Lot can only be in one of the official languages of the notice
* BT-300-Lot_C - BT-300-Lot can only be in one of the official languages of the notice

All BTs refered in the list are of type `text-multilingual` and the 3 Norwegian language codes are available for use for the fields. I must clearly have misunderstood something here, so how may I add Norwegian as one of the official languages of the notice in question?

**Pull request closed without merging**
