### PR TITLE
Prepare/1.4.2

### PR DESCRIPTION
**Pull request by rousso**

### CODE REVIEW

**Review by bertrand-lorentz — APPROVED** [review]
I was able to rune the eforms-notice-viewer on this branch, converting all notice XML examples using the EFX view templates without errors.
So OK for me.

**Review by pdonohoe — APPROVED** [review]

**Review by rousso — COMMENTED** [review]
@bertrand-lorentz Important!
The updates done manually by @pdonohoe must be reverted. 
Maybe the cleanest way to remove them is to create a new branch from my last commit and delete this branch and PR. Check with @meletev what's the cleanest way to remove them.

**Comment by bertrand-lorentz** [comment]
Added 2 commits to backport the changes to translations and view templates from the upcoming SDK 1.5.2.
Those changes are the same as the changes between 1.5.1 and 1.5.2.

**Comment by rousso** [comment]
Additonal commits reviewed. Looks good to me.

**Review by pdonohoe — APPROVED** [review]
It's probably fine

**Pull request merged**
