### PR TITLE
Update examples and generated files

### PR DESCRIPTION
**Pull request by bertrand-lorentz**
Latest updates to schematron rules, fields.json, and notice examples.

### CODE REVIEW

**Review by YvesJo — APPROVED** [review]
OK with me

**Comment by bertrand-lorentz** [comment]
I've added another commit for the view templates, so another approval is needed.

**Comment by rouschr** [comment]
One moment, I am now thinking about view templates and their draft status.
Initially nothing was draft but since the MDM UI allows to edit things that concept is being used.
The MDM code selects drafts because it needs the drafts for the UI, but the MDC does not want to deal with drafts.
So I will have to get into this with Laurent before we accept new view templates.

**Review by rouschr — APPROVED** [review]
According the Laurent the drafting thing is ok, I do not know the exact algorithm, the result looks ok and it does not break the export.

**Pull request merged**
