### PR TITLE
Prepare/1.3.3

### PR DESCRIPTION
**Pull request by rousso**

### CODE REVIEW

**Review by pdonohoe — APPROVED** [review]

**Review by rousso — COMMENTED** [review]
@bertrand-lorentz Important!
The updates done manually by @pdonohoe must be reverted. 
Maybe the cleanest way to remove them is to create a new branch from my last commit and delete this branch and PR. Check with @meletev what's the cleanest way to remove them.

**Comment by bertrand-lorentz** [comment]
Added 2 commits to backport the latest changes to translations and view templates from the upcoming SDK 1.4.2, and also solve 2 issues in the rules.

**Comment by bertrand-lorentz** [comment]
I was now able to rune the eforms-notice-viewer on this branch, converting all notice XML examples using the EFX view templates without errors.

**Comment by rousso** [comment]
Ok. I reviewd the additional commits. Looks good to me.

**Review by bertrand-lorentz — APPROVED** [review]

**Pull request merged**
