### PR TITLE
Feature/update schema next reg

### PR DESCRIPTION
**Pull request by YvesJo**
Covers changes for:

- EU Funds (Contract and Lot),
- Notice dispatch date esender

### CODE REVIEW

**Review by pdonohoe — APPROVED** [review]
These all look good to me. One minor comment: the definitions of efbc:TransmissionDate and efbc:TransmissionTime are not listed in alphabetical order in EFORMS-ExtensionApex-2.3.xsd

**Comment by bertrand-lorentz** [comment]
OK for me too.
@YvesJo : Please indicate if you want to make a change to address the comment of Paul, otherwise I'll merge this as it is.

**Comment by YvesJo** [comment]
> These all look good to me. One minor comment: the definitions of efbc:TransmissionDate and efbc:TransmissionTime are not listed in alphabetical order in EFORMS-ExtensionApex-2.3.xsd

Basic components first (efbc) and aggregate components after (efac), may be the reason for the observation?

**Comment by pdonohoe** [comment]
> These all look good to me. One minor comment: the definitions of efbc:TransmissionDate and efbc:TransmissionTime are not listed in alphabetical order in EFORMS-ExtensionApex-2.3.xsd

Stupid me! I didn't take into account the prefixes for the basic components followed by the aggregate components.

**Pull request merged**
