### PR TITLE
Update generated files for SDK 1.8.0

### PR DESCRIPTION
**Pull request by bertrand-lorentz**
This is the bulk of the changes for SDK 1.8.0.
The diff is large, so better look at individual commits.

⚠️ The checks are reporting "real" issues in the notice type definitions, tickets for these have been filed.

### CODE REVIEW

**Review by pdonohoe — APPROVED** [review]

**Review by YvesJo — APPROVED** [review]

**Review by YvesJo — COMMENTED** [review]
1.8 should also include PR #467

**Comment by bertrand-lorentz** [comment]
> 1.8 should also include PR #467

I have approved PR #467. Up to you to get other approvals if needed, and merge it into develop.

**Comment by YvesJo** [comment]
> > 1.8 should also include PR #467
> 
> I have approved PR #467. Up to you to get other approvals if needed, and merge it into develop.

PR #467 is now merged.

**Review by YvesJo — APPROVED** [review]

**Review by rouschr — APPROVED** [review]
Looks good.

**Review by rouschr — APPROVED** [review]

**Comment by bertrand-lorentz** [comment]
This PR has been going on for while, and has been previously approved.
So I'll merge this into develop and create a new PR for the next corrections.

**Pull request merged**
